"""Add payment attempts table and session attempt tracking

Revision ID: f07e4aac028d
Revises: 87f32a03d60c
Create Date: 2026-06-29 20:56:22.034213

"""
from alembic import op
import sqlalchemy as sa


revision = 'f07e4aac028d'
down_revision = '87f32a03d60c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
