"""remove_seller_id_from_checkouts

Revision ID: 57fcfdb642c2
Revises: 5fd91ec51db1
Create Date: 2026-06-24 23:38:05.249853

"""
from alembic import op
import sqlalchemy as sa


revision = '57fcfdb642c2'
down_revision = '5fd91ec51db1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('checkouts_seller_id_fkey'), 'checkouts', type_='foreignkey')
    op.drop_column('checkouts', 'seller_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('checkouts', sa.Column('seller_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('checkouts_seller_id_fkey'), 'checkouts', 'sellers', ['seller_id'], ['id'])
    # ### end Alembic commands ###
