"""remove_discounted_pricing_from_checkouts

Revision ID: 59d17e6243b9
Revises: 57fcfdb642c2
Create Date: 2026-06-24 23:41:37.325075

"""
from alembic import op
import sqlalchemy as sa


revision = '59d17e6243b9'
down_revision = '57fcfdb642c2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('checkouts', 'final_amount')
    op.drop_column('checkouts', 'coupon_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('checkouts', sa.Column('coupon_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True))
    op.add_column('checkouts', sa.Column('final_amount', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
