"""remove_product_id_from_checkouts

Revision ID: 5fd91ec51db1
Revises: 0001
Create Date: 2026-06-24 22:42:36.786172

"""
from alembic import op
import sqlalchemy as sa


revision = '5fd91ec51db1'
down_revision = '0001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_checkouts_user_id'), table_name='checkouts')
    op.drop_constraint(op.f('checkouts_product_id_fkey'), 'checkouts', type_='foreignkey')
    op.drop_column('checkouts', 'product_id')
    op.drop_index(op.f('ix_orders_checkout_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_user_id'), table_name='orders')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_orders_user_id'), 'orders', ['user_id'], unique=False)
    op.create_index(op.f('ix_orders_checkout_id'), 'orders', ['checkout_id'], unique=False)
    op.add_column('checkouts', sa.Column('product_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('checkouts_product_id_fkey'), 'checkouts', 'products', ['product_id'], ['id'])
    op.create_index(op.f('ix_checkouts_user_id'), 'checkouts', ['user_id'], unique=False)
    # ### end Alembic commands ###
